#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

hr=0
min=1
while ((hr <= 12));
do
	echo "Hour: $hr"
	while ((min <= 59));
	do
		echo "$min"
		((min++))
	done
	min=1
	((hr++))
done
